<script type='text/javascript' src='../js/jquery-1.11.0.min.js'></script>
<script type='text/javascript' src='../js/jquery-migrate-1.2.1.min.js'></script>
<script type='text/javascript' src='../js/jquery.ui.core.min.js'></script>
<script type='text/javascript' src='../js/jquery.easing.1.3.js'></script>
<script type='text/javascript' src='../js/jquery.epicfullscreen.js'></script>
<script type='text/javascript' src='../js/jquery.epicHover-fadeZoom.js'></script>
<script type='text/javascript' src='../js/jquery.epicslider.js'></script>
<script type='text/javascript' src='../js/jquery.flexslider-min-edited.js'></script>
<script type='text/javascript' src='../js/jquery.mobile-touch-swipe-1.0.js'></script>
<script type='text/javascript' src='../js/jquery.fancybox-1.3.4.pack.js'></script>
<script type='text/javascript' src='../js/settings.js'></script>
<script type='text/javascript' src='../js/common.js'></script>
<script type='text/javascript' src='../js/udt_shortcodes.js'></script>
<script type='text/javascript' src='http://maps.googleapis.com/maps/api/js?sensor=false'></script>
<script type='text/javascript' src='../js/contact.js'></script>